/**
 * Runtime validation of secrets/bindings that can't be checked at build time
 * (Cloudflare secrets don't exist until deploy). Throws a named error that
 * the caller turns into a clear, logged, user-visible failure — we never
 * want a form that silently does nothing because a key was never set.
 */
export class ConfigError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ConfigError";
  }
}

/** Alias for readability — `Env` is the global type generated by `wrangler types`, augmented in src/worker-env.d.ts. */
export type EnquiryRuntimeEnv = Env;

export function requireD1(env: EnquiryRuntimeEnv): D1Database {
  if (!env.DB) {
    throw new ConfigError("D1 binding 'DB' is not configured (check wrangler.jsonc d1_databases / Cloudflare dashboard binding)");
  }
  return env.DB;
}

export function getIpHashSalt(env: EnquiryRuntimeEnv): string {
  if (!env.IP_HASH_SALT) {
    throw new ConfigError("IP_HASH_SALT is not set — required to rate-limit without storing raw IPs");
  }
  return env.IP_HASH_SALT;
}

export function getRateLimits(env: EnquiryRuntimeEnv) {
  return {
    perIpPerHour: Number(env.ENQUIRY_RATE_LIMIT_PER_IP_PER_HOUR ?? "5"),
    perPhonePerDay: Number(env.ENQUIRY_RATE_LIMIT_PER_PHONE_PER_DAY ?? "3"),
    globalPerHour: Number(env.ENQUIRY_RATE_LIMIT_GLOBAL_PER_HOUR ?? "40"),
    resendDailyCap: Number(env.RESEND_DAILY_CAP ?? "100"),
    resendMonthlyCap: Number((env as unknown as Record<string, unknown>).RESEND_MONTHLY_CAP ?? "3000"),
  };
}
