export interface Jewel {
  slug: string; name: string; category: string; collection: string;
  price: number; material: string; weight: string; description: string; detail: string;
  shape: 'necklace' | 'earrings' | 'ring' | 'bangle'; stone: string;
}
export const jewels: Jewel[] = [
  { slug: 'chand-baoli', name: 'Chand Baoli', category: 'Necklaces', collection: 'The Stepwell Edit', price: 186000, material: '18K yellow gold · green quartz', weight: '18.4 g indicative gross weight', description: 'A crescent of stepped gold, with a single green centre.', detail: 'Articulated links follow the collarbone. The pendant takes its rhythm from the descending terraces of a Rajasthan stepwell; the reverse stays smooth against fabric.', shape: 'necklace', stone: '#638876' },
  { slug: 'gulabi-drops', name: 'Gulabi Drops', category: 'Earrings', collection: 'The Pink City Edit', price: 64500, material: '18K yellow gold · rose quartz', weight: '6.2 g indicative gross weight', description: 'Soft pink stones, held in a fine architectural frame.', detail: 'A compact day-to-evening drop with a post-and-butterfly closure. A satin gold border brings a quiet contrast to the polished rose quartz centre.', shape: 'earrings', stone: '#c98a92' },
  { slug: 'surya-signet', name: 'Surya Signet', category: 'Rings', collection: 'Everyday Heirlooms', price: 42000, material: '18K yellow gold · citrine', weight: '4.1 g indicative gross weight', description: 'A small sun for the hand. Substantial, never loud.', detail: 'The oval face sits low for everyday wear. A softly tapered shank balances the stone, with a brushed finish on the shoulders and a polished interior.', shape: 'ring', stone: '#c99b43' },
  { slug: 'rekha-cuff', name: 'Rekha Cuff', category: 'Bangles', collection: 'Everyday Heirlooms', price: 112000, material: '18K yellow gold · unadorned', weight: '12.8 g indicative gross weight', description: 'Two fine lines. One beautifully open gesture.', detail: 'An open cuff with rounded terminals and a softly hammered surface. Designed to be worn alone; the opening is a design feature, not an adjustable hinge.', shape: 'bangle', stone: '#d4b779' },
  { slug: 'neel-pendant', name: 'Neel Pendant', category: 'Necklaces', collection: 'Everyday Heirlooms', price: 58000, material: '18K yellow gold · blue onyx', weight: '5.7 g indicative gross weight', description: 'An inky blue accent on a fine gold chain.', detail: 'A small faceted pendant hangs from a 42 cm chain with an illustrative 3 cm extender. Its open setting lets the reverse of the stone remain visible.', shape: 'necklace', stone: '#496b8b' },
  { slug: 'jali-drops', name: 'Jali Drops', category: 'Earrings', collection: 'The Stepwell Edit', price: 82000, material: '18K yellow gold · green quartz', weight: '8.1 g indicative gross weight', description: 'Light passing through a little lattice of gold.', detail: 'Stepped frames echo the shade and symmetry of a jali screen. The long drop is paired with a deliberately small stud to keep the profile balanced.', shape: 'earrings', stone: '#638876' },
  { slug: 'gulabi-ring', name: 'Gulabi Ring', category: 'Rings', collection: 'The Pink City Edit', price: 49500, material: '18K yellow gold · rose quartz', weight: '4.8 g indicative gross weight', description: 'A blush-coloured centre with a petal-soft edge.', detail: 'The cushion setting is framed with tiny gold beads. A rounded band keeps the silhouette soft, with proportions intended for a single statement ring.', shape: 'ring', stone: '#c98a92' },
  { slug: 'aabha-bangle', name: 'Aabha Bangle', category: 'Bangles', collection: 'The Pink City Edit', price: 138000, material: '18K yellow gold · rose quartz', weight: '14.6 g indicative gross weight', description: 'A clean oval interrupted by a flash of pink.', detail: 'A narrow oval bangle with a single rose quartz accent. The illustrated clasp is integrated into the edge so the gold line reads as one continuous shape.', shape: 'bangle', stone: '#c98a92' },
];
export const categories = ['Necklaces', 'Earrings', 'Rings', 'Bangles'];
export const enquiry = '/contact?category=Jewellery&demo=sunehri-atelier';
export const inr = (value: number) => `₹${value.toLocaleString('en-IN')}`;
