/**
 * Augments the auto-generated `Env` interface (worker-configuration.d.ts,
 * regenerated by `npm run cf:typegen`) with secret bindings that don't
 * appear there because Cloudflare secrets are never written to wrangler.jsonc
 * — they're set with `wrangler secret put <NAME>` and only exist at runtime.
 * TypeScript interface declaration merging combines this with the
 * generated `interface Env` automatically.
 */
interface EnvSecrets {
  RESEND_API_KEY?: string;
  TURNSTILE_SECRET_KEY?: string;
  IP_HASH_SALT?: string;
}

// `import { env } from "cloudflare:workers"` is typed as `Cloudflare.Env`, while
// bindings elsewhere use the plain global `Env` — both need the augmentation.
interface Env extends EnvSecrets {}
declare namespace Cloudflare {
  interface Env extends EnvSecrets {}
}
